.TH AcidWM 1 acidwm
.SH NAME
.I acidwm
\- floating window manager for X11.
.SH BINDINGS
.TP
.B M\-Return
Start
.BR urxvt (1).
.TP
.B M\-q
Kill window.
.TP
.B M\-Tab
Focus next window.
.TP
.B M\-Shift\-Tab
Focus previous window.
.TP
.B M\-{h,j,k,l}
Move selected window {left,down,up,right}.
.TP
.B M\-Shift\-{h,j,k,l}
Resize selected window {left,down,up,right}.
.TP
.B M\-y
Teleport selected window to the top-left corner.
.TP
.B M\-u
Teleport selected window to the top-right corner.
.TP
.B M\-b
Teleport selected window to the bottom-right corner.
.TP
.B M\-n
Teleport selected window to the bottom-left corner.
.TP
.B M\-s
Teleport selected window to the center.
.TP
.B M\-a
Maximize(toggle) selected window.
.TP
.B M\-m
Maximize(toggle) selected window vertically.
.TP
.B M\-Shift\-m
Maximize(toggle) selected window horizontally.
.TP
.B M\-{1..n}
Switch to the nth workspace.
.TP
.B M\-{[,]}
Switch to previous,next workspace.
.TP
.B M\-Grave
Switch to the prior workspace.
.TP
.B M\-Shift\-{1..n}
Move focused window to the nth workspace.
.TP
.B M\-Button1
Dragging the mouse will move the selected window.
.TP
.B M\-Button3
Dragging the mouse will resize the selected window.
.TP
.B M\-Shift\-e
Quit acidwm.
.SH BUGS
.I acidwm
is under active development. Please report all bugs to the author.
.SH AUTHOR
Sina Pinto <sina.pinto at gmail.com>

